'use client'

import { useEffect, useMemo, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Bell, ChevronRight, CircleHelp, Coins, Copy, Download, Fuel, History, LayoutDashboard, MoreHorizontal, Plus, Send, Settings, ShieldCheck, Wallet, X, Zap } from 'lucide-react'

const ease = [0.16, 1, 0.3, 1] as const
const navItems = [
  { label: 'Dashboard', icon: LayoutDashboard },
  { label: 'Bots', icon: Zap },
  { label: 'Wallet', icon: Wallet },
  { label: 'Earn', icon: Coins },
  { label: 'Account', icon: Settings },
]

function PulseMark({ size = 34 }: { size?: number }) {
  return <svg aria-label="TradePulse mark" role="img" width={size} height={size} viewBox="0 0 40 40" fill="none"><path d="M3 21h7l3-9 6 18 5-14 3 5h10" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /><circle cx="37" cy="21" r="1.7" fill="#34D399" /></svg>
}

function GradientPanel({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`gradient-panel ${className}`}>{children}</div> }

function BootScreen({ onComplete }: { onComplete: () => void }) {
  const [step, setStep] = useState(0)
  const steps = ['verifying session…', 'syncing ledger…', 'loading desk…']
  useEffect(() => { const interval = window.setInterval(() => setStep((current) => Math.min(current + 1, 2)), 650); const done = window.setTimeout(onComplete, 2400); return () => { window.clearInterval(interval); window.clearTimeout(done) } }, [onComplete])
  return <motion.div className="boot-screen" exit={{ opacity: 0 }} transition={{ duration: .65, ease }}><div className="boot-mark"><PulseMark size={76} /></div><div className="boot-line" /><div className="boot-copy"><strong>TRADE<span>PULSE</span></strong><div className="boot-status"><span className="status-dot" />{steps[step]}</div></div></motion.div>
}

function Sidebar({ active, setActive }: { active: string; setActive: (value: string) => void }) { return <aside className="sidebar"><div className="brand"><PulseMark /><span>TRADE<span>PULSE</span></span></div><div className="desk-label">WORKSPACE</div><nav className="side-nav">{navItems.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${active === label ? 'active' : ''}`} onClick={() => setActive(label)}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><CircleHelp size={18} /><span>Help center</span></button><div className="profile"><div className="avatar">JD</div><div><strong>Jordan Davis</strong><small>Pro account</small></div><MoreHorizontal size={17} /></div></div></aside> }
function BottomNav({ active, setActive }: { active: string; setActive: (value: string) => void }) { return <nav className="bottom-nav">{navItems.map(({ label, icon: Icon }) => <button key={label} className={`bottom-item ${active === label ? 'active' : ''}`} onClick={() => setActive(label)}><span className="bottom-icon">{active === label && <i /> }<Icon size={19} /></span>{active === label && <span>{label}</span>}</button>)}</nav> }

function Header() { return <header className="topbar"><div className="mobile-brand"><PulseMark size={27} /><span>TRADE<span>PULSE</span></span></div><div className="page-heading"><span className="eyebrow">WORKSPACE / OVERVIEW</span><h1>Dashboard</h1></div><div className="welcome"><span className="eyebrow">GOOD MORNING</span><strong>Jordan</strong></div><div className="top-actions"><div className="live-indicator"><i />LIVE</div><button className="icon-button notification" aria-label="3 notifications"><Bell size={18} /><b>3</b></button><div className="top-avatar" aria-label="Jordan Davis avatar">JD</div></div></header> }

function CountUp({ value, decimals = 2, prefix = '$' }: { value: number; decimals?: number; prefix?: string }) { const [current, setCurrent] = useState(0); useEffect(() => { let frame = 0; const start = performance.now(); const tick = (now: number) => { const progress = Math.min((now - start) / 900, 1); setCurrent(value * (1 - Math.pow(1 - progress, 3))); if (progress < 1) frame = requestAnimationFrame(tick) }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame) }, [value]); return <>{prefix}{current.toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}</> }

function BalanceHero() { return <GradientPanel className="balance-hero reveal-card"><div className="panel-heading"><div><span className="eyebrow">TOTAL EQUITY</span><button className="visibility" aria-label="Hide balance">•••</button></div><span className="positive-chip">+12.84%</span></div><div className="balance"><CountUp value={24892.42} /></div><div className="balance-change">+$2,836.12 <span>this month</span></div><div className="balance-breakdown"><div><span>AVAILABLE</span><strong><CountUp value={8420.35} /></strong></div><div><span>INVESTED</span><strong><CountUp value={16472.07} /></strong></div></div><div className="hero-chart"><svg viewBox="0 0 600 100" preserveAspectRatio="none" aria-label="Equity growth chart"><path d="M0 81 C35 78 42 72 62 75 S95 53 115 64 S153 56 176 61 S208 45 235 51 S263 65 285 45 S320 48 345 35 S373 43 398 30 S427 42 452 24 S480 33 505 19 S550 27 600 7" fill="none" stroke="#34D399" strokeWidth="2" /></svg></div></GradientPanel> }

const bots = [{ name: 'Memecoin', allocation: '$4,250.00', equity: '$5,084.20', percent: 78, gain: '+19.63%', state: 'running', compound: '100%' }, { name: 'Synthetic', allocation: '$8,600.00', equity: '$8,112.44', percent: 46, gain: '-5.67%', state: 'paused', compound: '50%' }]
function BotRing({ percent, state }: { percent: number; state: string }) { return <div className={`bot-ring ${state}`} style={{ '--progress': `${percent * 3.6}deg` } as React.CSSProperties}><div className="ring-core"><i /></div></div> }
function MiniSparkline({ negative = false }: { negative?: boolean }) { return <svg className={`mini-sparkline ${negative ? 'negative' : ''}`} viewBox="0 0 120 38" preserveAspectRatio="none" aria-label="Bot equity sparkline"><path d={negative ? 'M2 10 C20 9 24 18 38 14 S57 22 72 17 S91 25 118 30' : 'M2 30 C17 27 21 19 35 24 S54 9 70 18 S87 8 101 12 S112 6 118 3'} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg> }
function BotCard({ bot }: { bot: typeof bots[number] }) { return <GradientPanel className="bot-card reveal-card"><div className="bot-card-top"><BotRing percent={bot.percent} state={bot.state} /><div className="bot-copy"><div className="bot-title"><strong>{bot.name}</strong><span className={`status-chip ${bot.state}`}><i />{bot.state}</span></div><span className="bot-allocation">Allocation {bot.allocation}</span><div className="bot-equity"><strong>{bot.equity}</strong><span className={bot.state === 'paused' ? 'down' : 'up'}>{bot.gain}</span></div></div></div><div className="bot-card-bottom"><MiniSparkline negative={bot.state === 'paused'} /><span className="compound-chip">COMPOUND {bot.compound}</span></div></GradientPanel> }

function StatChips() { return <div className="stat-chips reveal-card">{[['RUNNING BOTS', '01'], ['PAUSED', '01'], ['ALERTS', '03'], ['TIER', 'PRO'], ['SLOTS', '02 / 05']].map(([label, value]) => <div className="stat-chip" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div> }
function PriceStrip() { const prices = [['BTC/USD', '$67,842.10', '+2.41%', true], ['ETH/USD', '$3,842.66', '+1.08%', true], ['SOL/USD', '$182.44', '-0.74%', false], ['PEPE/USD', '$0.0000124', '+8.92%', true]]; return <div className="price-strip reveal-card">{prices.map(([name, price, change, up]) => <div className="ticker" key={name}><span>{name}</span><strong>{price}</strong><small className={up ? 'up' : 'down'}>{up ? '↗' : '↘'} {change}</small></div>)}</div> }
function Activity() { const items = [['Memecoin bot', 'Equity rebalance', '+$84.20', '2m', 'complete'], ['Synthetic bot', 'Risk threshold reached', '-$42.80', '18m', 'review'], ['Deposit received', 'USDC · Wallet', '+$1,250.00', '1h', 'complete']]; return <GradientPanel className="activity-card reveal-card"><div className="section-heading"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Ledger activity</h2></div><button className="view-all">View all <ChevronRight size={14} /></button></div><div className="activity-list">{items.map(([title, sub, amount, time, status]) => <div className="activity-row" key={title}><div className="activity-info"><strong>{title}</strong><small>{sub}</small></div><span className={`activity-status ${status}`}>{status}</span><div className="activity-amount"><strong className={amount.startsWith('+') ? 'up' : 'down'}>{amount}</strong><small>{time}</small></div></div>)}</div></GradientPanel> }
function DemoBanner() { return <GradientPanel className="demo-banner reveal-card"><div className="demo-mark"><PulseMark size={28} /></div><div><span className="eyebrow">PRACTICE MODE</span><h2>Try a $50 virtual memecoin demo</h2><p>Explore the desk with zero risk. Your balance stays untouched.</p></div><button aria-label="Try demo"><ChevronRight size={17} /></button></GradientPanel> }
function EmptyBots() { return <GradientPanel className="empty-bots"><svg viewBox="0 0 120 38" aria-label="Flatlined pulse"><path d="M2 20h28l8-9 9 18 8-9h63" fill="none" stroke="currentColor" strokeWidth="2" /></svg><p>No bots are running yet.</p><button>Launch your first bot <ChevronRight size={14} /></button></GradientPanel> }

const walletActions = [{ label: 'Deposit', icon: Download }, { label: 'Withdraw', icon: Send }, { label: 'History', icon: History }, { label: 'Activity', icon: Zap }]
function WalletCard({ label, value, detail, accent = '' }: { label: string; value: string; detail?: string; accent?: string }) { return <GradientPanel className="wallet-stat"><span className="eyebrow">{label}</span><strong className={accent}>{value}</strong>{detail && <small>{detail}</small>}</GradientPanel> }
function StepRail({ current }: { current: number }) { return <div className="step-rail">{['ASSET', 'NETWORK', 'CONFIRM'].map((step, index) => <div className={index < current ? 'done' : index === current ? 'current' : ''} key={step}><b>0{index + 1}</b><span>{index < current ? '✓' : step}</span>{index < 2 && <i />}</div>)}</div> }
function WalletOverview({ setView }: { setView: (view: string) => void }) { return <div className="wallet-grid"><div className="wallet-stat-grid"><WalletCard label="AVAILABLE" value="$8,420.35" detail="Ready to deploy" accent="mint" /><WalletCard label="LOCKED" value="$1,280.00" detail="Until 24 Sep" /><WalletCard label="TOTAL EQUITY" value="$24,892.42" detail="+12.84% this month" accent="mint" /><WalletCard label="HIGH-WATER MARK" value="$26,104.18" detail="Set 12 Aug" /></div><GradientPanel className="gas-card"><div className="section-heading"><div><span className="eyebrow">NETWORK GAS TANK</span><h2>Keep actions moving</h2></div><Fuel size={18} /></div><div className="gas-meter"><div><strong>72%</strong><small>~$14.40 remaining</small></div><div className="gas-track"><i /></div></div><label className="toggle-row"><span>Auto-fill when low<small>Uses available USDC</small></span><input type="checkbox" defaultChecked /><i /></label></GradientPanel><div className="wallet-actions">{walletActions.map(({ label, icon: Icon }) => <button key={label} onClick={() => setView(label === 'History' ? 'Ledger' : label)}><span><Icon /></span><strong>{label}</strong><ChevronRight /></button>)}</div><GradientPanel className="wallet-promo"><ShieldCheck /><div><span className="eyebrow">CUSTODY CONTROL</span><h2>Your funds stay yours.</h2><p>Every movement is recorded, verified, and visible in your ledger.</p></div></GradientPanel></div> }
function DepositFlow() { const [step, setStep] = useState(0); const [copied, setCopied] = useState(false); return <div className="wallet-flow"><StepRail current={step} /><GradientPanel className="flow-card"><div className="flow-title"><div><span className="eyebrow">DEPOSIT · USDC</span><h2>{step === 0 ? 'Choose an asset' : step === 1 ? 'Choose a network' : 'Send USDC to TradePulse'}</h2></div><span className="secure-chip"><ShieldCheck /> SECURE</span></div>{step === 0 && <div className="choice-grid">{['USDT', 'USDC'].map((asset, i) => <button className={i === 1 ? 'selected' : ''} key={asset} onClick={() => setStep(1)}><span className="coin-mark">{asset[0]}</span><strong>{asset}</strong><small>{i === 1 ? 'USD Coin' : 'Tether USD'}</small><ChevronRight /></button>)}</div>}{step === 1 && <div className="choice-grid">{[['Base', 'Low fees · ~2 min'], ['Ethereum', 'Higher fees · ~5 min'], ['Solana', 'Fast · ~1 min']].map(([network, note]) => <button key={network} onClick={() => setStep(2)}><span className="network-mark" /><strong>{network}</strong><small>{note}</small><ChevronRight /></button>)}</div>}{step === 2 && <><div className="qr-placeholder"><div className="qr-grid" /><small>SCAN TO DEPOSIT USDC ON BASE</small></div><div className="copy-field"><code>0x71F4...9aC28D</code><button onClick={() => { setCopied(true); window.setTimeout(() => setCopied(false), 1200) }}>{copied ? '✓' : <Copy />}</button></div><div className="warning-block"><strong>Send USDC on Base only</strong><span>Sending another asset or network may permanently lose funds.</span></div><label className="amount-field"><span>EXPECTED AMOUNT</span><input placeholder="0.00 USDC" inputMode="decimal" /></label><button className="primary-action" onClick={() => setStep(0)}>I made this deposit <ChevronRight /></button></>}</GradientPanel><GradientPanel className="blocking-banner"><X /><div><strong>Deposits temporarily unavailable</strong><span>We’re syncing the Base network. Try again shortly.</span></div><button>Check status</button></GradientPanel><DepositTimeline /></div> }
function DepositTimeline() { return <div className="timeline"><span className="eyebrow">DEPOSIT TIMELINE</span>{['Detected', 'Verified', 'Credited'].map((label, i) => <div className="timeline-row" key={label}><i className={i === 0 ? 'active' : ''}>{i === 0 ? '✓' : i + 1}</i><div><strong>{label}</strong><small>{i === 0 ? 'Waiting for an incoming transaction' : 'Pending detection'}</small></div><span className="status-chip review">pending</span></div>)}</div> }
function Ledger({ setView }: { setView: (view: string) => void }) { const rows = [['USDC deposit', '+$1,250.00', 'verified', 'Today · 09:12'], ['Bot allocation', '-$4,250.00', 'complete', 'Yesterday · 18:42'], ['Withdrawal', '-$800.00', 'pending', '18 Sep · 13:08'], ['Gas refill', '-$12.40', 'complete', '17 Sep · 10:20']]; return <div className="ledger-screen"><div className="ledger-header"><div><span className="eyebrow">WALLET / HISTORY</span><h2>Ledger history</h2></div><button className="view-all" onClick={() => setView('Wallet')}>Overview <ChevronRight /></button></div><div className="filter-chips"><button className="active">All</button><button>Deposits</button><button>Withdrawals</button><button>Bot activity</button></div><GradientPanel className="ledger-card">{rows.map(([title, amount, status, date]) => <div className="ledger-row" key={title}><div><strong>{title}</strong><small>{date} · Base</small></div><span className={`activity-status ${status}`}>{status}</span><code className={amount.startsWith('+') ? 'mint' : ''}>{amount}</code></div>)}</GradientPanel><div className="minimum-warning"><span>!</span><div><strong>Below-minimum deposit</strong><p>Received <code>12.00 USDC</code> · minimum <code>25.00 USDC</code> · remaining <code>13.00 USDC</code></p><small>Send the remaining amount to the same address to credit this deposit.</small></div></div></div> }
function WalletScreen() { const [view, setView] = useState('Wallet'); return view === 'Wallet' ? <WalletOverview setView={setView} /> : view === 'Ledger' ? <Ledger setView={setView} /> : <DepositFlow /> }

function Dashboard() { return <div className="dashboard-grid"><BalanceHero /><StatChips /><section className="bots-section reveal-card"><div className="section-heading"><div><span className="eyebrow">AUTOMATION</span><h2>My Bots <small>02</small></h2></div><button className="view-all">Manage <ChevronRight size={14} /></button></div><div className="bot-grid">{bots.map((bot) => <BotCard key={bot.name} bot={bot} />)}</div></section><PriceStrip /><Activity /><DemoBanner /><div className="sync-time">LAST SYNCED 09:42:18 UTC · ALL SYSTEMS NOMINAL</div></div> }

export default function TradePulseShell() { const [booted, setBooted] = useState(false); const [active, setActive] = useState('Dashboard'); return <AnimatePresence mode="wait">{!booted ? <BootScreen key="boot" onComplete={() => setBooted(true)} /> : <motion.div key="app" className="app-shell" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Sidebar active={active} setActive={setActive} /><main className="main-content"><Header />{active === 'Dashboard' ? <Dashboard /> : active === 'Wallet' ? <WalletScreen /> : <GradientPanel className="empty-state"><Zap size={24} /><h2>{active} is ready</h2><p>Your workspace will appear here.</p></GradientPanel>}</main><BottomNav active={active} setActive={setActive} /></motion.div>}</AnimatePresence> }
